### PR TITLE
issue-280 : fixed trace-indicator generation

### LINKED ISSUE #280: correct trace-indicator shall be formed for callback of /v1/regard-updated-link
The callback of /v1/regard-updated-link is /v1/update-operation-key. Currently, the callback is being sent with incorrect trace-indicators.

For example, if /v1/regard-updated-link is having trace-indicator=1 in request parameter, the callback is formed as below (like with trace-indicator 2, 3 etc.,) Instead it shall be formed like 1.1, 1.2 etc..,

```
{
  'content-type': 'application/json',
  accept: 'application/json',
  user: 'User Name',
  originator: 'OperationKeyManagement',
  'x-correlator': '4d4d5e5e-1a1a-2b2b-3c3c-446655440000',
  'trace-indicator': '2',
  'customer-journey': 'Unknown value',
  'operation-key': 'Operation key not yet provided.'
}
--------------------------
{
  'content-type': 'application/json',
  accept: 'application/json',
  user: 'User Name',
  originator: 'OperationKeyManagement',
  'x-correlator': '4d4d5e5e-1a1a-2b2b-3c3c-446655440000',
  'trace-indicator': '3',
  'customer-journey': 'Unknown value',
  'operation-key': 'Operation key not yet provided.'
}
```

### PR DESCRIPTION
**Pull request by DanaSunal**
Fixes #280

### CODE REVIEW

File: server/utils/HttpClient.js [hunk 1]
```diff
@@ -41,7 +41,7 @@ module.exports = class HttpClient {
     if (traceIndicator == undefined || traceIndicator === '') {
       this.#traceIndicator = '0'; // it is incremented when service execution is called
     } else {
-      this.#traceIndicator = traceIndicator;
+      this.#traceIndicator = traceIndicator + ".0";
```
Comment (PrathibaJee) [inline server/utils/HttpClient.js:44]: Trace indicator count starts with 1. Shall we change ".0" to ".1".

**Review by PrathibaJee — CHANGES_REQUESTED** [review]

File: server/utils/HttpClient.js (hunk 1 above)
Comment (DanaSunal) [reply server/utils/HttpClient.js:44]: No. This is just constructor. When the trace-indicator is first used, it's incremented (line 72). It's also explained in the comment on line 42.

Comment (PrathibaJee) [reply server/utils/HttpClient.js:44]: Thanks for the explanation.

**Review by PrathibaJee — APPROVED** [review]
